import Image from "next/image";
import Nearai from './assets/nearai.png';

export default function Project() {
  return (
    <section id="project" className="py-20 bg-black">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Title "Project" */}
        <div className="text-center mb-20">
          <h2 className="text-3xl font-extrabold text-white">Project Canvas</h2>
          <div className="mt-2 border-b-4 border-[#00EC97] w-28 mx-auto"></div>
        </div>
        {/* Project Catalog */}
        <div className="mt-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 justify-items-center">
          {/* Example Project Card */}
          <div className="bg-[#11141B] rounded-lg overflow-hidden shadow-lg w-full sm:w-4/5 md:w-full">
            {/* Image */}
            <Image src={Nearai} alt="NEAR AI" className="w-full h-50 object-cover"/>
            {/* Content */}
            <div className="p-6">
              <a href="https://paras.id/collection/near-ai-by-lunairefinenear">
                <h3 className="text-2xl font-semibold text-white">NEAR AI</h3>
                <p className="mt-4 text-gray-400 text-justify">NEAR AI is a collection of anime-style NFTs generated by AI using Generate Trait and published on the NEAR network.</p>
              </a>            
            </div>
            {/* Footer with three labels */}
            <div className="flex justify-left space-x-2 py-2 rounded-b-lg ml-5 mb-2">
              <span className="bg-[#005253] text-[#abf8f3] px-2 py-1 rounded-lg text-xs">NEAR</span>
              <span className="bg-[#005253] text-[#abf8f3] px-2 py-1 rounded-lg text-xs">NFT</span>
            </div>
          </div>
          {/* Duplicate the above card for additional projects */}
          <div className="bg-[#11141B] rounded-lg overflow-hidden shadow-lg w-full sm:w-4/5 md:w-full">
            {/* Image */}
            <Image src={Nearai} alt="NEAR AI" className="w-full h-50 object-cover"/>
            {/* Content */}
            <div className="p-6">
              <a href="https://paras.id/collection/near-ai-by-lunairefinenear">
                <h3 className="text-2xl font-semibold text-white">NEAR AI</h3>
                <p className="mt-4 text-gray-400 text-justify">NEAR AI is a collection of anime-style NFTs generated by AI using Generate Trait and published on the NEAR network.</p>
              </a>            
            </div>
            {/* Footer with three labels */}
            <div className="flex justify-left space-x-2 py-2 rounded-b-lg ml-5 mb-2">
              <span className="bg-[#005253] text-[#abf8f3] px-2 py-1 rounded-lg text-xs">NEAR</span>
              <span className="bg-[#005253] text-[#abf8f3] px-2 py-1 rounded-lg text-xs">NFT</span>
            </div>
          </div>
          <div className="bg-[#11141B] rounded-lg overflow-hidden shadow-lg w-full sm:w-4/5 md:w-full">
            {/* Image */}
            <Image src={Nearai} alt="NEAR AI" className="w-full h-50 object-cover"/>
            {/* Content */}
            <div className="p-6">
              <a href="https://paras.id/collection/near-ai-by-lunairefinenear">
                <h3 className="text-2xl font-semibold text-white">NEAR AI</h3>
                <p className="mt-4 text-gray-400 text-justify">NEAR AI is a collection of anime-style NFTs generated by AI using Generate Trait and published on the NEAR network.</p>
              </a>            
            </div>
            {/* Footer with three labels */}
            <div className="flex justify-left space-x-2 py-2 rounded-b-lg ml-5 mb-2">
              <span className="bg-[#005253] text-[#abf8f3] px-2 py-1 rounded-lg text-xs">NEAR</span>
              <span className="bg-[#005253] text-[#abf8f3] px-2 py-1 rounded-lg text-xs">NFT</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
